In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
X_train=SC.fit_transform(X_train)
X_test=SC.transform(X_test)

In [9]:
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

In [10]:
X_test

array([[ 0.89459283, -0.08863026, -0.06746417,  1.02378711, -0.50466988],
       [ 0.53757957, -0.22180837, -0.06746417, -0.97676557, -0.50466988],
       [ 0.60898222,  1.57449152,  0.76341038,  1.02378711,  1.98149332],
       ...,
       [ 1.10880078,  1.20785059, -0.89833872,  1.02378711, -0.50466988],
       [ 1.75142463,  1.34905148, -0.06746417,  1.02378711, -0.50466988],
       [ 1.60861933, -0.92299913, -0.89833872, -0.97676557, -0.50466988]])

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
param_grid = {
    'fit_intercept': [True, False],
    'copy_X': [True, False],
    'n_jobs': [1, -1],
    'positive': [False, True]}
grid = GridSearchCV(LinearRegression(),param_grid, refit=True, verbose=3, n_jobs=-1)
regressor=grid.fit(X_train,y_train)
y_pred=regressor.predict(X_test)
y_pred

Fitting 5 folds for each of 16 candidates, totalling 80 fits


array([11494.66343731,  9939.13858872, 37674.80720199, 15971.18826784,
        6867.78163959,  3551.94938018,  1012.29574839, 14160.72797496,
        8827.05979112,  7296.70496722,  4197.7766988 , 10170.95536354,
        9077.94710705,  4236.14697304, 27449.33042523, 11262.99180505,
       11200.63995584,  5526.20791971,  8052.77553825, 26345.85480423,
       33386.71543976, 14157.21695329, 11241.94212032, 32390.79221085,
        4436.36725655,  8628.219732  ,   693.86854098, 10238.19385142,
        4179.47173701, 10253.94053816,  8854.84846455, 40226.06811219,
       15914.47100708, 14077.59765777, 24114.57927836,  4624.55278387,
       12975.14771438, 30712.12454447, 33111.91224936,  3769.86458779,
        3579.73805361,  4369.93709213, 29872.42396689, 39094.38817786,
       27808.93372292,  4767.43465047, 11157.07440884,  7669.47372023,
        3172.96690729, 10787.40754866,  5045.64574469,  3196.58598555,
       33172.5515643 , 37789.47291737, 16330.70751607,  6517.72052354,
      

In [12]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.7894429387120754

In [13]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'copy_X': True, 'fit_intercept': True, 'n_jobs': 1, 'positive': True}:


In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_copy_X  \
0        0.032928      0.006369         0.003844        0.002585         True   
1        0.013989      0.011435         0.002665        0.002715         True   
2        0.004633      0.001752         0.000707        0.001415         True   
3        0.005491      0.004126         0.001522        0.003043         True   
4        0.002036      0.002520         0.002666        0.003518         True   
5        0.003716      0.004000         0.001949        0.002496         True   
6        0.002529      0.003876         0.000237        0.000474         True   
7        0.006298      0.005132         0.000000        0.000000         True   
8        0.003853      0.002473         0.001404        0.002335        False   
9        0.004100      0.002476         0.002138        0.002751        False   
10       0.003223      0.002808         0.003838        0.002331        False   
11       0.004028      0.003956         0.000604        0.001209        False   
12       0.004677      0.004345         0.000000        0.000000        False   
13       0.003524      0.002324         0.001319        0.002639        False   
14       0.002223      0.002840         0.002386        0.002614        False   
15       0.003113      0.002264         0.002641        0.002311        False   

   param_fit_intercept param_n_jobs param_positive  \
0                 True            1          False   
1                 True            1           True   
2                 True           -1          False   
3                 True           -1           True   
4                False            1          False   
5                False            1           True   
6                False           -1          False   
7                False           -1           True   
8                 True            1          False   
9                 True            1           True   
10                True           -1          False   
11                True           -1           True   
12               False            1          False   
13               False            1           True   
14               False           -1          False   
15               False           -1           True   

                                               params  split0_test_score  \
0   {'copy_X': True, 'fit_intercept': True, 'n_job...           0.763511   
1   {'copy_X': True, 'fit_intercept': True, 'n_job...           0.763511   
2   {'copy_X': True, 'fit_intercept': True, 'n_job...           0.763511   
3   {'copy_X': True, 'fit_intercept': True, 'n_job...           0.763511   
4   {'copy_X': True, 'fit_intercept': False, 'n_jo...          -0.698095   
5   {'copy_X': True, 'fit_intercept': False, 'n_jo...          -0.698095   
6   {'copy_X': True, 'fit_intercept': False, 'n_jo...          -0.698095   
7   {'copy_X': True, 'fit_intercept': False, 'n_jo...          -0.698095   
8   {'copy_X': False, 'fit_intercept': True, 'n_jo...           0.763511   
9   {'copy_X': False, 'fit_intercept': True, 'n_jo...           0.763511   
10  {'copy_X': False, 'fit_intercept': True, 'n_jo...           0.763511   
11  {'copy_X': False, 'fit_intercept': True, 'n_jo...           0.763511   
12  {'copy_X': False, 'fit_intercept': False, 'n_j...          -0.698095   
13  {'copy_X': False, 'fit_intercept': False, 'n_j...          -0.698095   
14  {'copy_X': False, 'fit_intercept': False, 'n_j...          -0.698095   
15  {'copy_X': False, 'fit_intercept': False, 'n_j...          -0.698095   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.702938           0.730655           0.695551   
1            0.703146           0.730655           0.695634   
2            0.702938           0.730655           0.695551   
3            0.703146           0.730655           0.695634   
4           -0.586805          -0.459207          -0.600488   
5           -0.586653          -0.45