In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
X_train=SC.fit_transform(X_train)
X_test=SC.transform(X_test)

In [9]:
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

In [10]:
X_test

array([[ 0.89459283, -0.08863026, -0.06746417,  1.02378711, -0.50466988],
       [ 0.53757957, -0.22180837, -0.06746417, -0.97676557, -0.50466988],
       [ 0.60898222,  1.57449152,  0.76341038,  1.02378711,  1.98149332],
       ...,
       [ 1.10880078,  1.20785059, -0.89833872,  1.02378711, -0.50466988],
       [ 1.75142463,  1.34905148, -0.06746417,  1.02378711, -0.50466988],
       [ 1.60861933, -0.92299913, -0.89833872, -0.97676557, -0.50466988]])

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],'max_features': [None,'sqrt','log2'],'n_estimators':[50,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose=3,n_jobs=-1)
regressor=grid.fit(X_train,y_train)
y_pred=regressor.predict(X_test)
y_pred

Fitting 5 folds for each of 24 candidates, totalling 120 fits


array([ 9843.326844  ,  9272.1685728 , 43613.011643  , 13882.99687   ,
        9441.088714  , 10424.245436  ,  1855.589988  , 12555.5771346 ,
        7928.4401398 ,  5665.928356  ,  6400.6223216 , 12792.9102356 ,
        8177.436699  ,  7914.5057002 , 25599.9055082 , 12535.8542002 ,
       13108.8750634 ,  5019.7230212 ,  7221.2236584 , 32419.543828  ,
       24336.872608  , 18828.2285778 ,  9954.0243556 , 31368.9243054 ,
        4228.2573888 ,  6349.8474922 ,  3380.32664   ,  8804.1980722 ,
        3661.389327  , 11106.4277074 ,  7587.4905642 , 44083.536745  ,
       15094.1454472 , 14376.3946996 , 19470.0576592 ,  4332.087402  ,
        9509.3152138 , 36503.824628  , 39478.2351818 ,  2447.364816  ,
        5865.9762742 ,  3157.91837   , 20581.9844312 , 46403.6827876 ,
       36818.515247  ,  3461.654014  , 12821.4576372 ,  6735.64542   ,
        7407.0462    , 13027.934722  ,  4302.229191  ,  4741.2097036 ,
       28324.4250378 , 44859.5773348 , 11633.797852  ,  9857.1443856 ,
      

In [12]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8655274694475142

In [13]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 50}:


In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.270003      0.013902         0.009447        0.001704   
1        0.516415      0.006662         0.024681        0.008132   
2        0.208277      0.009289         0.010467        0.001950   
3        0.415381      0.016474         0.018472        0.002897   
4        0.216757      0.020188         0.009196        0.001306   
5        0.416817      0.013414         0.023695        0.009068   
6        0.279688      0.022244         0.006879        0.001439   
7        0.555143      0.015352         0.018898        0.003883   
8        0.218092      0.010440         0.018285        0.012228   
9        0.427558      0.009968         0.020527        0.007213   
10       0.224562      0.010912         0.010765        0.003546   
11       0.452716      0.019060         0.019753        0.002790   
12       1.266092      0.118508         0.016260        0.004121   
13       3.156953      0.227535         0.030575        0.006041   
14       1.006227      0.019225         0.013805        0.003136   
15       1.946391      0.043357         0.022106        0.002324   
16       1.019864      0.037907         0.014853        0.002088   
17       1.916229      0.092165         0.033841        0.002294   
18       0.595323      0.007865         0.020258        0.009124   
19       1.051358      0.047007         0.030971        0.008340   
20       0.413125      0.011411         0.016453        0.005967   
21       0.832326      0.034985         0.030236        0.005561   
22       0.419422      0.013220         0.011974        0.002470   
23       0.619865      0.027219         0.022183        0.006089   

   param_criterion param_max_features param_n_estimators  \
0    squared_error               None                 50   
1    squared_error               None                100   
2    squared_error               sqrt                 50   
3    squared_error               sqrt                100   
4    squared_error               log2                 50   
5    squared_error               log2                100   
6     friedman_mse               None                 50   
7     friedman_mse               None                100   
8     friedman_mse               sqrt                 50   
9     friedman_mse               sqrt                100   
10    friedman_mse               log2                 50   
11    friedman_mse               log2                100   
12  absolute_error               None                 50   
13  absolute_error               None                100   
14  absolute_error               sqrt                 50   
15  absolute_error               sqrt                100   
16  absolute_error               log2                 50   
17  absolute_error               log2                100   
18         poisson               None                 50   
19         poisson               None                100   
20         poisson               sqrt                 50   
21         poisson               sqrt                100   
22         poisson               log2                 50   
23         poisson               log2                100   

                                               params  split0_test_score  \
0   {'criterion': 'squared_error', 'max_features':...           0.864406   
1   {'criterion': 'squared_error', 'max_features':...           0.861384   
2   {'criterion': 'squared_error', 'max_features':...           0.852463   
3   {'criterion': 'squared_error', 'max_features':...           0.863451   
4   {'criterion': 'squared_error', 'max_features':...           0.871176   
5   {'criterion': 'squared_error', 'max_features':...           0.861025   
6   {'criterion': 'friedman_mse', 'max_features': ...           0.862035   
7   {'criterion': 'friedman_mse', 'max_features': ...           0.862594   
8   {'criterion': 'friedman_mse', 'max_features': ...           0.852823   
9   {'criterion': 'friedman_mse', 'max_fea