In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
X_train=SC.fit_transform(X_train)
X_test=SC.transform(X_test)

In [9]:
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

In [10]:
X_test

array([[ 0.89459283, -0.08863026, -0.06746417,  1.02378711, -0.50466988],
       [ 0.53757957, -0.22180837, -0.06746417, -0.97676557, -0.50466988],
       [ 0.60898222,  1.57449152,  0.76341038,  1.02378711,  1.98149332],
       ...,
       [ 1.10880078,  1.20785059, -0.89833872,  1.02378711, -0.50466988],
       [ 1.75142463,  1.34905148, -0.06746417,  1.02378711, -0.50466988],
       [ 1.60861933, -0.92299913, -0.89833872, -0.97676557, -0.50466988]])

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['squared_error','friedman_mse','absolute_error','poisson'],'max_features': [None,'sqrt','log2'],'n_estimators':[50,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose=3,n_jobs=-1)
regressor=grid.fit(X_train,y_train)
y_pred=regressor.predict(X_test)
y_pred

Fitting 5 folds for each of 24 candidates, totalling 120 fits


C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning: 
30 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
21 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 1467, in wrapper
    estimator._validate_params()
  File "C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\swath\anaconda3\Lib\site-packages

array([10648.0546578 ,  9045.7581732 , 43094.847525  , 13864.8145305 ,
       11041.5312797 , 10648.6575877 ,  2445.0723935 , 11362.9018312 ,
        8426.134496  ,  6633.769123  ,  6106.6603375 , 13480.9142845 ,
        8346.6172797 ,  6780.897669  , 22770.0156075 , 12427.2943371 ,
       14061.8818907 ,  4080.9319247 ,  6909.4965546 , 32142.0457271 ,
       24514.5214115 , 18551.6243312 , 10412.5235627 , 27818.1650209 ,
        2419.9083745 ,  6774.7276302 ,  4278.1428274 ,  8498.1016856 ,
        3689.9896855 , 12624.8913159 ,  8679.8849076 , 44879.6515791 ,
       14987.271766  , 12985.117563  , 17306.6544126 ,  4330.7493135 ,
        9522.8217836 , 37826.2599959 , 38533.801203  ,  2450.5277078 ,
        5819.1917659 ,  3212.5528556 , 19965.9560876 , 46483.2810115 ,
       38020.7841008 ,  4236.8142901 , 12702.666019  ,  6540.0661015 ,
        5902.9121571 , 13040.1051952 ,  4176.245288  ,  4494.8545416 ,
       26974.0078085 , 45428.9029696 , 11654.6944115 , 11312.9220149 ,
      

In [12]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8698139180112616

In [13]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}:


In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.503938      0.020724         0.026472        0.009059   
1        1.119621      0.095296         0.030576        0.000707   
2        0.447843      0.076890         0.019263        0.001742   
3        0.920656      0.075556         0.031482        0.005459   
4        0.441891      0.028353         0.018482        0.002983   
5        0.886833      0.056183         0.036462        0.005265   
6        0.602372      0.058771         0.024035        0.008819   
7        1.110824      0.092097         0.029219        0.002844   
8        0.458820      0.042551         0.017167        0.003226   
9        0.872929      0.028748         0.037533        0.007468   
10       0.472672      0.017327         0.018258        0.002430   
11       0.848329      0.045081         0.031547        0.003819   
12       0.000902      0.001803         0.000000        0.000000   
13       0.000570      0.000707         0.000000        0.000000   
14       0.000493      0.000620         0.000000        0.000000   
15       0.004038      0.003151         0.000000        0.000000   
16       0.003516      0.003249         0.000000        0.000000   
17       0.001011      0.001238         0.000000        0.000000   
18       0.605396      0.052699         0.017109        0.002792   
19       1.237256      0.072537         0.028434        0.003909   
20       0.497069      0.030623         0.016486        0.003521   
21       0.994981      0.098582         0.030286        0.002202   
22       0.543047      0.083805         0.022508        0.006195   
23       0.964435      0.072762         0.028592        0.004339   

   param_criterion param_max_features param_n_estimators  \
0    squared_error               None                 50   
1    squared_error               None                100   
2    squared_error               sqrt                 50   
3    squared_error               sqrt                100   
4    squared_error               log2                 50   
5    squared_error               log2                100   
6     friedman_mse               None                 50   
7     friedman_mse               None                100   
8     friedman_mse               sqrt                 50   
9     friedman_mse               sqrt                100   
10    friedman_mse               log2                 50   
11    friedman_mse               log2                100   
12  absolute error               None                 50   
13  absolute error               None                100   
14  absolute error               sqrt                 50   
15  absolute error               sqrt                100   
16  absolute error               log2                 50   
17  absolute error               log2                100   
18         poisson               None                 50   
19         poisson               None                100   
20         poisson               sqrt                 50   
21         poisson               sqrt                100   
22         poisson               log2                 50   
23         poisson               log2                100   

                                               params  split0_test_score  \
0   {'criterion': 'squared_error', 'max_features':...           0.862070   
1   {'criterion': 'squared_error', 'max_features':...           0.862998   
2   {'criterion': 'squared_error', 'max_features':...           0.865195   
3   {'criterion': 'squared_error', 'max_features':...           0.866666   
4   {'criterion': 'squared_error', 'max_features':...           0.850904   
5   {'criterion': 'squared_error', 'max_features':...           0.866913   
6   {'criterion': 'friedman_mse', 'max_features': ...           0.861449   
7   {'criterion': 'friedman_mse', 'max_features': ...           0.859518   
8   {'criterion': 'friedman_mse', 'max_features': ...           0.862847   
9   {'criterion': 'friedman_mse', 'max_fea