In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
SC=StandardScaler()
X_train=SC.fit_transform(X_train)
X_test=SC.transform(X_test)

In [9]:
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

In [10]:
X_test

array([[ 0.89459283, -0.08863026, -0.06746417,  1.02378711, -0.50466988],
       [ 0.53757957, -0.22180837, -0.06746417, -0.97676557, -0.50466988],
       [ 0.60898222,  1.57449152,  0.76341038,  1.02378711,  1.98149332],
       ...,
       [ 1.10880078,  1.20785059, -0.89833872,  1.02378711, -0.50466988],
       [ 1.75142463,  1.34905148, -0.06746417,  1.02378711, -0.50466988],
       [ 1.60861933, -0.92299913, -0.89833872, -0.97676557, -0.50466988]])

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],
              'C':[10,50,100,500,1000,2000,3000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
regressor=grid.fit(X_train,y_train)
y_pred=regressor.predict(X_test)
y_pred

Fitting 5 folds for each of 56 candidates, totalling 280 fits


array([ 9882.23553045,  8684.53726052, 47863.91492801, 12571.3296839 ,
       10503.41343965,  4754.93723665,  1443.94974332, 11161.657231  ,
        7435.84538836,  5371.62749203,  6792.36540753, 10061.14110577,
        7632.07502973,  4871.76871538, 25340.31666642, 10702.78951231,
       12523.59208885,  3559.80058082,  6538.68332237, 24014.94367286,
       25935.15514707, 12148.61708249,  9691.29174851, 30533.71413143,
        1963.47262983,  4967.98361807,  4445.33159778,  8003.49970394,
        4385.68529386,  8313.99557978,  7894.30531574, 51334.29195097,
       13004.91484206, 10251.92921715, 12711.42308371,  4153.88138193,
        8739.42694068, 35968.17012455, 35436.61473361,  2077.05999458,
        5945.32507383,  3376.59733561, 27298.90556466, 44665.58571445,
       32712.02939249,  3248.44366366, 10704.52721091,  7044.43520973,
        4729.54504139, 12142.93055349,  2793.08923534,  2960.73592137,
       30936.72609045, 42934.61243677, 11849.41436963,  3311.33971211,
      

In [12]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8598930084494356

In [13]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:


In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.075575      0.012759         0.036603        0.006808      10   
1        0.100575      0.042893         0.014502        0.007453      10   
2        0.079790      0.004902         0.013484        0.000737      10   
3        0.075299      0.017897         0.008580        0.004883      10   
4        0.084666      0.015356         0.057276        0.012961      10   
5        0.075908      0.008041         0.012937        0.002199      10   
6        0.072393      0.009271         0.021414        0.005016      10   
7        0.056655      0.006444         0.011204        0.006824      10   
8        0.073257      0.002924         0.034719        0.007608      50   
9        0.065195      0.007256         0.009469        0.008637      50   
10       0.081924      0.005689         0.015103        0.003029      50   
11       0.082633      0.012876         0.010265        0.002470      50   
12       0.075154      0.005689         0.042473        0.006481      50   
13       0.068071      0.004546         0.011398        0.002221      50   
14       0.081180      0.010800         0.015839        0.003850      50   
15       0.075113      0.004812         0.010383        0.003874      50   
16       0.087806      0.018185         0.037963        0.006860     100   
17       0.068785      0.004717         0.011452        0.004017     100   
18       0.084881      0.004601         0.015304        0.006936     100   
19       0.085165      0.009949         0.008937        0.001454     100   
20       0.078282      0.012793         0.037008        0.001931     100   
21       0.063794      0.005699         0.011335        0.000866     100   
22       0.081324      0.003503         0.016961        0.008184     100   
23       0.076889      0.006014         0.009968        0.001255     100   
24       0.101534      0.012491         0.038963        0.005298     500   
25       0.086721      0.010586         0.012478        0.003070     500   
26       0.091889      0.015735         0.013903        0.002204     500   
27       0.081474      0.003453         0.010686        0.001987     500   
28       0.125829      0.032897         0.068812        0.011415     500   
29       0.173872      0.022232         0.020922        0.005427     500   
30       0.162850      0.013527         0.026417        0.006373     500   
31       0.162757      0.008668         0.018330        0.003324     500   
32       0.198988      0.030480         0.072790        0.002050    1000   
33       0.189663      0.025949         0.019240        0.005096    1000   
34       0.182818      0.018263         0.029221        0.007915    1000   
35       0.179673      0.010844         0.017537        0.005261    1000   
36       0.205068      0.017206         0.071076        0.008669    1000   
37       0.192071      0.043949         0.020358        0.004826    1000   
38       0.168995      0.010639         0.022596        0.004160    1000   
39       0.173497      0.017646         0.018445        0.008683    1000   
40       0.196789      0.021440         0.071973        0.006072    2000   
41       0.335339      0.062546         0.017570        0.005694    2000   
42       0.169083      0.016048         0.036979        0.023401    2000   
43       0.240724      0.034556         0.019252        0.002168    2000   
44       0.199249      0.009762         0.074054        0.007620    2000   
45       0.300231      0.033743         0.018629        0.001470    2000   
46       0.172628      0.014082         0.025051        0.003201    2000   
47       0.213707      0.020882         0.021743        0.002431    2000   
48       0.235128      0.018042         0.072302        0.001222    3000   
49       0.496073      0.226545         0.023033        0.004517    3000   
50       0.177876      0.007863         0.025747        0.003082    3000   
51       0.246995      0.022879         0.018205    