In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
dataset=dataset.drop("User ID",axis=1)

In [7]:
dataset

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [8]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [9]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset["Purchased"]

In [10]:
indep.shape

(400, 3)

In [11]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
param_grid = {
    'criterion': ['gini', 'entropy'], 
    'max_features': ['sqrt', 'log2'],
    'splitter': ['best', 'random']
}
clf = DecisionTreeClassifier()
grid = GridSearchCV(clf, param_grid, refit=True, verbose=3, n_jobs=-1)
classifier = grid.fit(indep, dep)
y_pred = classifier.predict(indep)
print("Best parameters found: ", grid.best_params_)
print("Best cross-validation score: {:.2f}".format(grid.best_score_))


Fitting 5 folds for each of 8 candidates, totalling 40 fits
Best parameters found:  {'criterion': 'entropy', 'max_features': 'log2', 'splitter': 'random'}
Best cross-validation score: 0.85


In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(dep, y_pred)
print(cm)       

[[257   0]
 [  1 142]]


In [14]:
from sklearn.metrics import classification_report
clf_report = classification_report(dep, y_pred)

In [15]:
print(clf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       257
           1       1.00      0.99      1.00       143

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400



In [16]:
print(cm)

[[257   0]
 [  1 142]]


In [17]:
classifier.predict([[27,57000,0]])

C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [18]:
re=grid.cv_results_

In [19]:
table=pd.DataFrame.from_dict(re)

In [20]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.013701      0.003936         0.006983        0.004080   
1       0.010621      0.001180         0.008899        0.002889   
2       0.013462      0.004710         0.005767        0.003339   
3       0.009741      0.005106         0.007254        0.005187   
4       0.016497      0.006385         0.007429        0.003119   
5       0.009622      0.004530         0.009337        0.001415   
6       0.012421      0.004303         0.006728        0.004125   
7       0.007238      0.005483         0.011620        0.002926   

  param_criterion param_max_features param_splitter  \
0            gini               sqrt           best   
1            gini               sqrt         random   
2            gini               log2           best   
3            gini               log2         random   
4         entropy               sqrt           best   
5         entropy               sqrt         random   
6         entropy               log2           best   
7         entropy               log2         random   

                                              params  split0_test_score  \
0  {'criterion': 'gini', 'max_features': 'sqrt', ...             0.8000   
1  {'criterion': 'gini', 'max_features': 'sqrt', ...             0.8875   
2  {'criterion': 'gini', 'max_features': 'log2', ...             0.8375   
3  {'criterion': 'gini', 'max_features': 'log2', ...             0.8250   
4  {'criterion': 'entropy', 'max_features': 'sqrt...             0.7625   
5  {'criterion': 'entropy', 'max_features': 'sqrt...             0.8625   
6  {'criterion': 'entropy', 'max_features': 'log2...             0.8250   
7  {'criterion': 'entropy', 'max_features': 'log2...             0.8375   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0             0.9000             0.8625             0.8000             0.8125   
1             0.8625             0.8625             0.7875             0.7750   
2             0.8750             0.8875             0.8250             0.7375   
3             0.8875             0.8125             0.8125             0.7125   
4             0.8875             0.8750             0.7875             0.7625   
5             0.8750             0.8375             0.7625             0.7375   
6             0.8875             0.8625             0.8000             0.7625   
7             0.9250             0.8750             0.8000             0.8125   

   mean_test_score  std_test_score  rank_test_score  
0           0.8350        0.039843                2  
1           0.8350        0.045000                2  
2           0.8325        0.052797                4  
3           0.8100        0.056125                8  
4           0.8150        0.055000                6  
5           0.8150        0.055000                6  
6           0.8275        0.044300                5  
7           0.8500        0.045415                1