In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
dataset=dataset.drop("User ID",axis=1)

In [7]:
dataset

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [8]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [9]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset["Purchased"]

In [10]:
indep.shape

(400, 3)

In [11]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
param_grid = {
    'n_neighbors': [ 5, 10,50,100],  
    'weights': ['uniform', 'distance',None],  
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'] } 
grid = GridSearchCV(KNeighborsClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(indep, dep)
print("Best parameters found: ", grid.best_params_)
y_pred = grid.predict(indep)
print("Predictions: ", y_pred)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
Best parameters found:  {'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'distance'}
Predictions:  [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(dep, y_pred)
print(cm)       

[[257   0]
 [  1 142]]


In [14]:
from sklearn.metrics import classification_report
clf_report = classification_report(dep, y_pred)

In [15]:
print(clf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       257
           1       1.00      0.99      1.00       143

    accuracy                           1.00       400
   macro avg       1.00      1.00      1.00       400
weighted avg       1.00      1.00      1.00       400



In [16]:
print(cm)

[[257   0]
 [  1 142]]


In [17]:
grid.predict([[27,57000,0]])

C:\Users\swath\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [18]:
re=grid.cv_results_

In [19]:
table=pd.DataFrame.from_dict(re)

In [20]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.014843      0.003349         0.034553        0.001755   
1        0.009779      0.001892         0.012246        0.003405   
2        0.014046      0.004285         0.042923        0.006442   
3        0.020487      0.011471         0.052423        0.014732   
4        0.010619      0.006523         0.025851        0.013174   
5        0.009486      0.001202         0.032468        0.003548   
6        0.009026      0.001052         0.031914        0.003833   
7        0.007257      0.003145         0.011738        0.002163   
8        0.009652      0.003838         0.035997        0.005690   
9        0.005432      0.004067         0.031400        0.004607   
10       0.008525      0.004170         0.016962        0.004294   
11       0.009920      0.002503         0.031187        0.005939   
12       0.010652      0.001867         0.030114        0.003391   
13       0.008572      0.003709         0.011503        0.006463   
14       0.007251      0.005399         0.033859        0.003587   
15       0.006684      0.003276         0.031584        0.004202   
16       0.007829      0.002698         0.008472        0.003851   
17       0.010343      0.004634         0.028875        0.006600   
18       0.007525      0.005258         0.030390        0.000048   
19       0.008809      0.002649         0.008942        0.007243   
20       0.007164      0.004383         0.032669        0.005112   
21       0.006394      0.004608         0.034842        0.004158   
22       0.009408      0.003134         0.012589        0.004261   
23       0.007024      0.001520         0.032824        0.005626   
24       0.006739      0.003345         0.029106        0.001495   
25       0.010532      0.003266         0.006227        0.003347   
26       0.009121      0.001732         0.026454        0.004424   
27       0.009478      0.000928         0.027168        0.005687   
28       0.009402      0.004264         0.008409        0.003679   
29       0.007105      0.003762         0.029162        0.004893   
30       0.007678      0.004196         0.034914        0.007565   
31       0.008704      0.005125         0.007893        0.005208   
32       0.009930      0.003566         0.031987        0.006838   
33       0.006797      0.003334         0.036597        0.007608   
34       0.008005      0.001860         0.012982        0.004302   
35       0.010195      0.000119         0.032497        0.003175   
36       0.009235      0.002245         0.041720        0.010902   
37       0.010594      0.001323         0.015892        0.012447   
38       0.007297      0.003632         0.049645        0.018977   
39       0.011202      0.008366         0.052324        0.017563   
40       0.009800      0.001066         0.020214        0.016909   
41       0.009916      0.003365         0.042825        0.018097   
42       0.006666      0.005523         0.050954        0.014022   
43       0.007811      0.009125         0.021390        0.010768   
44       0.013208      0.007385         0.050786        0.010965   
45       0.009861      0.012642         0.056851        0.018490   
46       0.004707      0.004260         0.015829        0.003992   
47       0.007545      0.003665         0.028641        0.004355   

   param_algorithm param_n_neighbors param_weights  \
0             auto                 5       uniform   
1             auto                 5      distance   
2             auto                 5          None   
3             auto                10       uniform   
4             auto                10      distance   
5             auto                10          None   
6             auto                50       uniform   
7             auto                50      distance   
8             auto                50          None   
9             auto               100       uniform   
10            auto               100      distance   
11            auto     