In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
dataset=dataset.drop("User ID",axis=1)

In [7]:
dataset

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [8]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [9]:
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset["Purchased"]

In [10]:
indep.shape

(400, 3)

In [11]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
indep=sc.fit_transform(indep)

In [13]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
param_grid = {
    'C': [ 10,100],  
    'kernel': ['linear', 'rbf', 'poly','sigmoid'], 
    'gamma': ['scale','Auto'] } 
grid_search = GridSearchCV(estimator=SVC(),param_grid=param_grid,scoring='accuracy', refit=True,verbose=3, n_jobs=-1 ) 
grid_search.fit(indep, dep)
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_
y_pred = best_model.predict(indep)
print(f"Best parameters: {best_params}")

Fitting 5 folds for each of 16 candidates, totalling 80 fits
Best parameters: {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}


C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
40 fits failed out of a total of 80.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
16 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Admin\anaconda3\Lib\site-packages\

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(dep, y_pred)
print(cm)       

[[233  24]
 [ 11 132]]


In [15]:
from sklearn.metrics import classification_report
clf_report = classification_report(dep, y_pred)

In [16]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.95      0.91      0.93       257
           1       0.85      0.92      0.88       143

    accuracy                           0.91       400
   macro avg       0.90      0.91      0.91       400
weighted avg       0.92      0.91      0.91       400



In [17]:
print(cm)

[[233  24]
 [ 11 132]]


In [18]:
grid_search.predict([[27,57000,0]])

array([1], dtype=int64)

In [19]:
re=grid_search.cv_results_

In [20]:
table=pd.DataFrame.from_dict(re)

In [21]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.012792  1.719016e-03         0.003798        0.000748      10   
1        0.008396  1.495535e-03         0.005597        0.001199      10   
2        0.011792  1.938287e-03         0.003398        0.001496      10   
3        0.008795  1.599062e-03         0.004198        0.001599      10   
4        0.001601  4.907519e-04         0.000000        0.000000      10   
5        0.001397  4.874753e-04         0.000000        0.000000      10   
6        0.003798  3.760122e-03         0.000000        0.000000      10   
7        0.004797  6.611280e-03         0.000000        0.000000      10   
8        0.035380  3.439195e-03         0.002798        0.000748     100   
9        0.010594  2.243438e-03         0.004798        0.001166     100   
10       0.033780  1.133228e-02         0.002998        0.000632     100   
11       0.009195  2.134006e-03         0.002798        0.000979     100   
12       0.001600  1.199389e-03         0.000000        0.000000     100   
13       0.001200  3.997567e-04         0.000000        0.000000     100   
14       0.001599  7.994533e-04         0.000000        0.000000     100   
15       0.000999  3.568323e-07         0.000000        0.000000     100   

   param_gamma param_kernel  \
0        scale       linear   
1        scale          rbf   
2        scale         poly   
3        scale      sigmoid   
4         Auto       linear   
5         Auto          rbf   
6         Auto         poly   
7         Auto      sigmoid   
8        scale       linear   
9        scale          rbf   
10       scale         poly   
11       scale      sigmoid   
12        Auto       linear   
13        Auto          rbf   
14        Auto         poly   
15        Auto      sigmoid   

                                               params  split0_test_score  \
0     {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}             0.6875   
1        {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}             0.8875   
2       {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}             0.7375   
3    {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}             0.7625   
4      {'C': 10, 'gamma': 'Auto', 'kernel': 'linear'}                NaN   
5         {'C': 10, 'gamma': 'Auto', 'kernel': 'rbf'}                NaN   
6        {'C': 10, 'gamma': 'Auto', 'kernel': 'poly'}                NaN   
7     {'C': 10, 'gamma': 'Auto', 'kernel': 'sigmoid'}                NaN   
8    {'C': 100, 'gamma': 'scale', 'kernel': 'linear'}             0.6875   
9       {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}             0.8125   
10     {'C': 100, 'gamma': 'scale', 'kernel': 'poly'}             0.7250   
11  {'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}             0.8250   
12    {'C': 100, 'gamma': 'Auto', 'kernel': 'linear'}                NaN   
13       {'C': 100, 'gamma': 'Auto', 'kernel': 'rbf'}                NaN   
14      {'C': 100, 'gamma': 'Auto', 'kernel': 'poly'}                NaN   
15   {'C': 100, 'gamma': 'Auto', 'kernel': 'sigmoid'}                NaN   

    split1_test_score  split2_test_score  split3_test_score  \
0              0.9625             0.9000             0.7750   
1              0.9375             0.9125             0.8250   
2              0.9625             0.9125             0.8250   
3              0.7875             0.8625             0.7250   
4                 NaN                NaN                NaN   
5                 NaN                NaN                NaN   
6                 NaN                NaN                NaN   
7                 NaN                NaN                NaN   
8              0.9625             0.9000             0.7750   
9              0.9250             0.9000             0.8250   
10             0.9625             0.9125             0.8375   
11             0.7625             0.8625             0.6875   
12                NaN                NaN                NaN   
13      